# General
TIMEZONE = "US/Eastern"
SECRET_KEY = ""
ENVIRONMENT = "development"
FLASK_DOMAIN = "localhost"
FLASK_PORT = 6005
FRONTEND_DOMAIN = "http://localhost:5000"
FRONTEND_DOMAIN_UI = [
    "http://localhost",
    "http://localhost:8080",
    "http://localhost:3000",
    "http://52.34.40.39:8900/chatbot",
    "http://52.34.40.39:8900/"
]
HTTP_HTTPS = "http://"

NLU_THRESHOLD=0.8

MAX_LOGGING_LENGTH = 1000

# Database
MONGO_HOSTNAME = "mongodb"
MONGO_PORT = 27017
MONGO_AUTH_DATABASE = "rasadb"
MONGO_AUTH_USERNAME = "rasa"
MONGO_AUTH_PASSWORD = "rasa"
MONGO_APP_DATABASE = "rasadb"

[RASA_WEBHOOK]
URL = "http://rasa-core:5005"
TOKEN = "secret"

[INTENT_NAME_TO_DISPLAY]
greet="Initial Greeting"
input_screening_response="Response to a screening question"
job_screening="Begin Job screening"
explore_jobs="Explore jobs"
input_select_job="Job Selected"
input_resume_upload_data="Resume Uploaded"
affirm="Yes"
input_job_location="Preferred Job Location"
input_job_title="Preferred Job Title"
deny="No"