version: 1
disable_existing_loggers: False
 
# Define format of output logs (named 'simple').
formatters:
    simple:
        (): uvicorn.logging.DefaultFormatter
        format: '{LOG_PREFIX}: %(asctime)s,%(msecs)03d [%(threadName)s]- GATEWAY - %(levelname)-5s %(name)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
 
handlers:
    # Create console
    console:
        class: logging.StreamHandler
        stream: 'ext://sys.stdout'
        level: DEBUG
        formatter: simple
 
root:
    level: INFO
    handlers: [console]
